#!/bin/sh

FOLDER_SUFFIX=msvc64
TOOLSET=x86_64-w64-mingw32
PREFIX=
export lib_arch=X64

export CC='cl.exe'
#export CXX=$PREFIX-g++
#export CPP=$PREFIX-cpp
#export RANLIB=$PREFIX-ranlib
export PATH="/mnt/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64:$PATH"



