#!/bin/sh

FOLDER_SUFFIX=msvc32
TOOLSET=i686-w64-mingw32
PREFIX=

export lib_arch=X86

export CC='cl.exe'

#export CXX=$PREFIX-g++
#export CPP=$PREFIX-cpp
#export RANLIB=$PREFIX-ranlib
export PATH="/mnt/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin:$PATH"



