#!/bin/sh
#set -x
. common

PLATFORM=mingw
COMPILER=gcc
LIB_ARCH=x86
HOST_DEF=i686-w64-mingw32

export CC=$PREFIX-gcc
export CXX=$PREFIX-g++
export CPP=$PREFIX-cpp
export RANLIB=$PREFIX-ranlib
export PATH="/usr/i686-w64-mingw32/bin:$PATH"
#exec "$@"
