#!/bin/sh
#set -x
. $( dirname "${BASH_SOURCE[0]}")/common

PLATFORM=mingw32
COMPILER=gcc
LIB_ARCH=x64
FULLARCH=x86_64
HOST_DEF=x86_64-w64-mingw32
CROSS_PREFIX=${HOST_DEF}-

export PATH="/usr/mingw-w64/toolchain-x86_64/bin:$PATH"
export PATH="/mnt/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64:$PATH"
