#!/bin/sh
#set -x
. $( dirname "${BASH_SOURCE[0]}")/common

PLATFORM=mingw
COMPILER=msvc
LIB_ARCH=x86
HOST_DEF=i686-w64-mingw32
CROSS_PREFIX=
CROSSBUILDTREE=/usr/$HOST_DEF

export CC='cl.exe'
export PATH="/mnt/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin:$PATH"



